=== Rodez-IUT/dut-info2-filmprovider-JeanCharlesLuans/Part1-XML-DTD/resources/XML3/librairieDTD.dtd
<!-- Copyright -->
<!ENTITY copyright "&#xA9;Librairie &amp; Internet 2020">

<!-- IdentitÃ© d'un auteur -->
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ENTITY % identite "(nom, prenom?)">

<!-- Texte pouvant contenir des balise HTML -->
<!ELEMENT strong (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT img (#PCDATA)>
    <!ATTLIST img src CDATA #REQUIRED>
    <!ATTLIST img title CDATA #IMPLIED>
<!ENTITY % texteFormate "(#PCDATA | strong | em | img)*">

<!-- Librairie -->
<!ELEMENT librairie (en-tete, livre+)>

    <!ELEMENT en-tete %texteFormate;>

    <!ELEMENT livre (titre, (auteur+ | collectif), description, prix)>
    <!ATTLIST livre isbn ID #REQUIRED>

        <!ELEMENT  titre (#PCDATA)>

        <!ELEMENT auteur %identite;>


        <!-- Organisation d'auteur -->
        <!ELEMENT collectif (direction, membre)>

            <!ELEMENT direction %identite;>

            <!ELEMENT membre (#PCDATA)>

        <!-- Description du livre -->
        <!ELEMENT  description %texteFormate;>

        <!-- prix du livre -->
        <!ELEMENT prix EMPTY>
        <!ATTLIST prix valeur CDATA #REQUIRED>
        <!ATTLIST prix devise (euro | livre | dollar) "euro">
        <!ATTLIST prix tva NMTOKEN #FIXED "5.5">

=== Rodez-IUT/dut-info2-filmprovider-JeanCharlesLuans/Part1-XML-DTD/resources/XML3/librairie.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE librairie SYSTEM "librairieDTD.dtd">

<librairie>

    <en-tete>
        <img src="smah" title="Salut">Ceci est une image</img>
        &copyright;
        <em>CRDOC Rodez</em>
        <strong>A l'IUT de Rodez</strong>
    </en-tete>

    <livre isbn="7891">
        <titre>Le tour du monde en 80 jours</titre>
        <auteur>
            <nom>Vernes</nom>
            <prenom>Jules</prenom>
        </auteur>

        <description>
            <strong>Le tour du monde en 80</strong>
            <em>Fineas Fogg</em>
            <img src="/images" title="une planette">Illusatration</img>
        </description>

        <prix valeur="35" devise="dollar" tva="5.5"/>
    </livre>
</librairie>
